spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mos_burger_db?createDatabaseIfNotExist=true
    username: root
    password: 1100

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true